### ISSUE TITLE
Repeated Approach Command

### ISSUE THREAD

**Issue by h355t0ph3r** [Viir/bots#10]
Had a thought, a way to prevent the repeated "approach" command entry would be to have it once, then evaluate the window for a target that is within distance of a Miner I (I think that is the shortest distance).  If there isn't one, then enter command again, if there is, then lock on and enable lasers.

**Comment by Viir** [comment]
Can we see a recording of your scenario?

**Comment by h355t0ph3r** [comment]
I don't have the stuff to record it. It is after it warps to a belt, but
before it activates mining lasers.

**Comment by Viir** [comment]
I have published a guide on how to get the stuff to record it here: https://github.com/Viir/bots/blob/9aaf21d0d10f9f5b13d6513217baccee22b25caa/guide/failed-run-bot-did-not-find-botengine-program.md

When you use the botengine for Windows, it creates one directory in `%localappdata%\botengine\run-app-session` for each session.

Uploading the files from the directory of the session where you saw this is enough to share your scenario.

**Comment by cantcodenothing** [comment]
Hi. I've tried to use it at VMware, but cose it's lagging always, then bot clicks much times at undock, after it undocks, it clicks to plex>cargo and repeats if instantly, and don't warps to belt. I've wanted to ask about it, how can i do a delay after each click? Or setup delay in the sript? Sorry if i don't described the problem quite specifically or didn't try to figuring some befor asking (didn't get where to download this script).

**Comment by Viir** [comment]
I see the bot code already offers an app setting to customize a general delay. So we can increase the delay without changing the bot code. As long as you don't change the code, you don't need to download anything.
To increase the delay we can use this app-settings string:
`bot-step-delay=4000`
This increases the delay between bot steps to four seconds.
If you use the command-line, here is the full command:
```cmd
botengine  run  --app-settings="bot-step-delay=4000"  https://github.com/Viir/bots/tree/7d46d3f0c432433657e552552e451fbf9be45c65/implement/applications/eve-online/eve-online-mining-bot
```

Otherwise, you can download a script with this setting from https://catalog.botengine.org/63d2b10af9b7b7001c49cfc3eb63888b6905aa50fe18a4cb99caadd5cfcc4249/configure-run-app/eyJvbmxpbmVTZXNzaW9uIjpmYWxzZSwiYXBwU2V0dGluZ3MiOiJib3Qtc3RlcC1kZWxheT00MDAwIiwicGF1c2VBcHBLZXlzIjoiIiwic2Vzc2lvbkxlbmd0aExpbWl0IjoiIn0=

![image](https://user-images.githubusercontent.com/19209696/83940134-df9f8b80-a7d1-11ea-8008-445422c0201b.png)
