### ISSUE TITLE
I see no route in the info panel

### ISSUE THREAD

**Issue by pilaurent** [Viir/bots#2]
Hi Viir,
i've tried to follow carefully your guide on how to use the bot to travel from point A to B, but for some Reason i don't see any mouvement even if route is set.
To set a route in game, i'm right clicking on the **overview** then left clicking on **Set Destination**.
(Language is English)

This is was i have in the cmd

```
Bot F5B0B70ED5... in session '2019-11-20T06-05-48-AD3845B5F53D' is running. Press CTRL + ALT keys to pause the bot.
Last bot event was 0 seconds ago at 06-23-35.398. There are 0 tasks in progress ().
Status message from bot:

Last script run result is: Success: {"getMemoryMeasurementResult":{"completed":{"mainWindowId":"919606","reducedWithNamedNodesJson":"null"}}}
Current activity: Operate bot:
I see no route in the info panel. I will start when a route is set.
```

Can you please tell me how to do ?
Regards,
Pierre

**Comment by Viir** [comment]
Hi Pierre,
thank you for the feedback.
I am looking at the text that you copied from the bot. Because of the part which says `"reducedWithNamedNodesJson":"null"`, I see that the memory reading was not successful.

I heard from EVE Online users that the client sometimes automatically changes the settings to a configuration which prevents the current travel bot from reading the memory.
There was also a post on the forum about this issue at https://forum.botengine.org/t/last-measurement-failed/2792/8?u=viir

To fix this problem, repeat this step from the guide:

> + The bot we will use in this guide only works when the EVE Online client is configured to not run in 64-bit mode. Make sure that the setting `Run clients with 64 bit` is *disabled* for the EVE Online client. You can check this in the settings dialog shown in the screenshot below:
> 
> ![Settings Dialog in EVE Online](https://github.com/Viir/bots/raw/716d95a99ff6b0411deea7f357970c5de009f718/guide/eve-online/image/2019-10-08.eve-online-launcher-settings-dialog.png)

**Comment by Viir** [comment]
The newest versions of the bots now support the 64-bit game client. As long as you use the latest version, this problem should not occur anymore.
I changed the guides today to link to these new bots: https://github.com/Viir/bots/commit/1cdfd461285afeb66182db1252e78d72baac27a7

Also related, the announcement of 64-bit client support: https://forum.botengine.org/t/botengine-devlog/2183/32?u=viir
