### ISSUE TITLE
Show 0 mining modules and stuck at opening inventory

### ISSUE THREAD

**Issue by altaheer** [Viir/bots#37]
Hey!
Loved the 0 warp bot but Im trying to use the mining bot and it gets stuck at toggleing/expanding the inventory on my ship.
And also, it shows 0 mining modules although I have it.

How could I solve this?

**Comment by Viir** [comment]
Maybe the inventory and mining modules look slightly different in your game client. Such an issue is easily fixed by adding more training data. If you link the session recording archive of your session, I can take a look and adapt the bot to your game client. 
You can upload the file directly here in the GitHub issue. To get the archive for your session, see the guide at https://to.botengine.org/guide/how-to-report-an-issue-with-an-app-or-request-a-new-feature#getting-the-session-recording-archive
