### ISSUE TITLE
Bot cant find the overview window even tho its open

### ISSUE THREAD

**Issue by Sakrafina** [Viir/bots#58]
For some reason the bot doesnt see the overview window, so it undocks the ship but cant do anything after that step
{
  "botlabClientVersion": "2022-10-28",
  "botId": "999f03ff3e728e68fca5c065d924bb3f93bc425fcdebe042c5f5128787d1ebff",
  "initialBotSettingsHash": "e3b0c4",
  "sessionCustomName": "2022-11-10T13-58-20",
  "onlineSessionId": "4133a76c55408ed1840f",
  "lastBotStep": {
    "sessionAgeMilliseconds": 247709,
    "statusTextFromBot": "Session performance: times unloaded: 0, volume unloaded / m\u00B3: 0\n---\nCurrent reading: mining hold filled 0%. Shield HP at 100%. Found 0 mining modules. I do not see the drones window.\n\u002B I see no overview window, wait until undocking completed.\n\u002B\u002B Wait for progress in game\n----\nEVE Online framework status:\nLast reading from game client: 000063-243402: 0 rects containing 0 pixels\nLast result from volatile process is: Success: {\u0022ReadFromWindowResult\u0022:{\u0022Completed\u0022:{\u0022processId\u0022:14036,\u0022windowClientRectOffset\u0022:{\u0022x\u0022:8,\u0022y\u0022:31},\u0022readingId\u0022:\u0022000063-243402\u0022,\u0022im....\nCurrent activity: Operate bot"
  },
  "finishReason": null
}

**Comment by Viir** [comment]
Thank you for the report!
We made a new bot to work with that new appearance of the overview window in the game client. You can run it from <https://catalog.botlab.org/dc8a29c85e>

Since there is bot dc8a29c85e now, you don't need bot 999f03ff3e anymore.
You can switch all your EVE Online mining bot configurations to bot dc8a29c85e. It supports the same settings.

**Comment by Sakrafina** [comment]
wow thanks for the fast answer and problem solving!!! it works perfectly now
