### ISSUE TITLE
Problem with message box using bot 7aec4c539e (Eve Online Mining)

### ISSUE THREAD

**Issue by focabr** [Viir/bots#62]
Msg bot...

I see a message box to close.

I see no way to close this message box.

I am stuck here and need help to continue.

[play-session-2023-01-14T02-17-05-at-1829037-ms-summary.json.txt](https://github.com/Viir/bots/files/10416413/play-session-2023-01-14T02-17-05-at-1829037-ms-summary.json.txt)

**Comment by focabr** [comment]
![image](https://user-images.githubusercontent.com/4109361/212448441-5d3acac8-9019-4f35-a6cc-af5519d5f267.png)

**Comment by Viir** [comment]
Thank you for sharing your finding 👍 
I will probably get to adapt the bot next week.
Until the new bot is ready, you could change the game client settings to not show this message box. The appearance seems to depend on the configuration of the game client.

**Comment by Viir** [comment]
Thank you for sharing this finding 👍 
Using your screenshot, I can adapt the bot. Probably next week.
Until the new bot is ready, you could change the game client settings to not show this message box. The appearance seems to depend on the configuration of the game client.

**Comment by focabr** [comment]
thanks for your reply, as a workaround I increased bot-step-delay=2500, after that the message does not get to appear.

**Comment by Viir** [comment]
I have added bot b21ae94ac8 to fix this issue: https://github.com/Viir/bots/commit/fa2597f4a0ef08ad60ff5c884fe97bf9163ae6b7

You can run the new bot from https://catalog.botlab.org/b21ae94ac8

In the screenshot you posted, there is a button with a label 'OK'. You can close the message box by clicking on it.
The problem you saw happened because the representation of the 'OK' label is different from earlier observations. The bot was not anymore able to read the label because of these differences.
The linked commit adapts the reading of the buttons in message boxes to adapt to the new appearance in the game client.
The mining bot example already has a branch to click on a button if it is labeled 'OK' or 'Close' in a message box. So no changes were needed in selecting the next action in the Bot.elm module.

Along with the reading of the buttons, the commit introduces more of the framework for image-processing bots into the examples for EVE Online.

## Background for bot developers

We introduced image processing functionality in bots more than a year ago. In EVE Online, bots have been using screenshots, for example, to check the status of ship modules.
The update in January 2023 improves the functionality for image processing the BotLab client substantially. Most importantly, new functionality in the development tools helps automate more of the bot development process. The development tools now show the images and crops read by the bot in the session history. The graphical interface also offers the export of individual images, making training data collection easier.

**Comment by focabr** [comment]
Hi,

 even using the new bot, gave the same 
 problem with this message box.

[play-session-2023-01-22T15-12-11-at-206022-ms-summary.json.txt](https://github.com/Viir/bots/files/10474729/play-session-2023-01-22T15-12-11-at-206022-ms-summary.json.txt)

[bot-77319826fb664d2ab42f0d87ae897b2a326966adf7295b77ba1b4f6da16f5520.zip](https://github.com/Viir/bots/files/10474746/bot-77319826fb664d2ab42f0d87ae897b2a326966adf7295b77ba1b4f6da16f5520.zip)

![image](https://user-images.githubusercontent.com/4109361/213924428-1501c4cc-478a-49c0-a8f2-85da0b6ebc34.png)

**Comment by Viir** [comment]
I see you added information about a play session.
That play session did not use the new bot.

To use the new bot, select 'b21ae94ac8' in the 'Select Bot' view.

**Comment by Viir** [comment]
Some background information regarding the recordings and training data: The last image that you posted was derived from a memory reading. That is the kind of reading that already existed earlier and does not even contain the image data that we now use to read the labels on the buttons in the message boxes.
A session recording typically contains thousands of exportable images. Picking the right one for a given case sometimes takes some experience. That is why the recommendation for most people is to upload the complete recording. Then a developer can do the work of selecting the right part.
In this case, the most important image is in the 'Read from window' section of the event details view:
![image](https://user-images.githubusercontent.com/19209696/213931264-2549d883-a0f6-4561-892f-5186d85d92c8.png)

However, in this case, the overall development process uses the complete session recording to compose the test environment.

**Comment by focabr** [comment]
Hi, thanks for replying.

I was using a version of the BOT that is in beta, I had updated the eve-online-mining-bot to version 2023-01-21 before running the bot.

I sent the session recording files by email.

**Comment by Viir** [comment]
> I sent the session recording files by email.

Thank you, I received the `session-recording-2023-01-22T15-12-11.zip` and will work with that.

**Comment by Viir** [comment]
I fixed a bug in the framework which caused the bot to not detect the 'OK' label on the button: https://github.com/Viir/bots/commit/6c35f637bc7ffef25bd9c31993aa9ee67c3d023a

**Comment by focabr** [comment]
Viih,
I did the tests using 2 game clients with different themes and it worked very well.

Thanks a lot and good job.

**Comment by Viir** [comment]
Thank you for the thorough testing 👍
