### ISSUE TITLE
BOTs do not detect message box "set quantity"

### ISSUE THREAD

**Issue by focabr** [Viir/bots#67]
I don't know if this problem is old or not, when the BOT is moving ore from the mining hold to the fleet hangar and it is full, a message box appears and the BOT is not detecting this message box.

I am sent to email  session-recording-2023-01-31T22-56-25 and a small video.

![image](https://user-images.githubusercontent.com/4109361/215905299-c44e5939-055c-4313-9990-1301ad7ea8fa.png)

**Comment by Viir** [comment]
Reading these buttons will be a new feature. You were the first to collect the training data.
Thank you for that 👍

**Comment by Viir** [comment]
Today I got around to looking into 'session-recording-2023-01-31T22-56-25'
The program code already covers the dialog window you see there. You can also see that in the status text for event 555:
![image](https://user-images.githubusercontent.com/19209696/217916994-14e9852e-ea7c-44de-a439-423bb7f780eb.png)

Here we can see the bot detected the label 'OK' on one of the buttons.

A bug in the framework caused it to select the wrong effect in event 554.
This bug caused the drag&drop effect we can see in the video.
We fixed this bug in the meantime, and you can get the new framework from https://github.com/Viir/bots/tree/67affdc9b2a099510319a2169d29d66182543fec/implement/applications/eve-online/eve-online-mining-bot

**Comment by focabr** [comment]
I updated the "botlab client v2023-02-10" and also the "bot version 2023-02-08" before running the tests again, both are now in the latest version.

Running the bot the same problem happens, I recorded a new session-recording only now smaller. I sent an email to support@botlab.org.

If you think it's necessary, I can record a new video and send it to you, I didn't because the bot did exactly the same thing as before.

Thanks again for your help.

**Comment by Viir** [comment]
In session-recording-2023-02-11T13-14-56, we have a new situation: In event 363, we see the UI element is now contained in a new container of type 'HybridWindow'. The change of the labels from 'MessageBox' to 'HybridWindow' in the game client was why the bot did not interpret that node as a message box.

I updated the examples here: https://github.com/Viir/bots/commit/65808b86a68e35c8b4fe7078fe1dd5fa872a5d86

This commit updated the parsing up to the button group. Since the button group is now available in the memory reading parsing of individual buttons should work as with the other kinds of message boxes before.

**Comment by focabr** [comment]
Viir,

Excellent, it worked perfectly!

Sorry for the delay I had tested it, I missed updating and closing here.

**Comment by Viir** [comment]
Awesome!

**Comment by Viir** [comment]
Since a few people reported issues with detecting the button labels, we found that sometimes a setting of the game client UI scaling to `110%` caused the label detection to fail with the current implementation. At the moment, I recommend that you set the UI scaling to 100% in the display settings.

![image](https://github.com/user-attachments/assets/c8f47209-387c-4f7a-b0e0-8483a9680aac)
